apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJZbTlzYjNweU9tZHBkR2gxWWw5d1lYUmZNVEZCVGtSYVRreEJNRlZKTVVsVlRrNUVSWGRKYmw5Rk4zcE5iR2xzY0hZeVEwcDZka2hQYVZwSldHRXpjVlZzYjNocFJrOUNkMEZ0YWxSSVprMW9ZVFpaVDBGVVZWbFZVbFpUYVRnNFpFaFVUZz09IgogICAgfQogIH0KfQo=
type: kubernetes.io/dockerconfigjson
